---
# Trigger configuration file. Actions executed with order in which they
# appears in this file

# Subscribe and lanuch addtional queries to gather some more information about devices
# For tasmota commands, please visit:
#   https://github.com/arendst/Sonoff-Tasmota/wiki/Commands
#

# Network info
- mqtt:
    subscribe:
      topic: 'stat/{{ trigger_topic[1] }}/STATUS5'
      type: 'json'
      varname: 'status5'
    publish:
      topic: 'cmnd/{{ trigger_topic[1] }}/status'
      message: '5'

# Be carefull with shell commands and always take into consideration system security
- shell:
    command: 'echo "Last update: $(date)"'
    type: 'string'
    varname: 'description'

# Finally generate templates
- template:
    src: '{{ templates_dir }}/openhab/tasmota-{{ trigger_payload.Module|default("Generic")|pathescape|replace(" ", "_") }}.j2'
    dest: '{{ items_dir }}/{{ trigger_topic[1]|pathescape }}.mqr.items'

