---

# Remove offline devices
- shell:
    command: |
      FILE="{{items_dir}}/{{ trigger_topic[1]|pathescape }}.mqr.items"
      if [ -f "$FILE" ] && [ "{{ trigger_payload|pathescape }}" = "Offline" ]; then
        mv -f ${FILE} ${FILE}-offline
      fi

    type: 'string'
    varname: 'mv'

